version: "3.9"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - user-files:/app/storage
    environment:
      # App-konfig (matchar server.py som läser DB_* variabler)
      - PYTHONUNBUFFERED=1
      - FLAG_2=${FLAG_2}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=tatou
      - DB_USER=tatou
      - DB_PASSWORD=${MARIADB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mariadb:11.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=tatou
      - MARIADB_USER=tatou
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./db/tatou.sql:/docker-entrypoint-initdb.d/10-tatou.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root --password=$MARIADB_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=64M
      - MEMORY_LIMIT=256M
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - server
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  db-data:
  user-files:
