global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'tatou'
    static_configs:
      - targets: ['server:5000']
  - job_name: 'tatou-flag-watchdog'
    static_configs:
      - targets: ['flag-watchdog:9101']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

