name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ./server[dev]

      - name: Build and start stack
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml --env-file .env.ci up -d db server
          # Give containers time to initialize
          sleep 15

      - name: Wait for server healthcheck
        run: |
          for i in {1..12}; do
            if curl -sf http://localhost:5000/healthz; then
              echo "Server is ready!"
              break
            fi
            echo "Waiting for server..."
            sleep 5
          done

      - name: Run tests with coverage
        env:
          BASE_URL: http://localhost:5000
        run: pytest --cov=tatou --cov-report=xml
