name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:11.4
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: tatou
          MARIADB_USER: tatou
          MARIADB_PASSWORD: tatou
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping -h 127.0.0.1 -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ./server[dev]

      - name: Build and start server
        run: |
          docker compose -f docker-compose.yml up -d server
          sleep 10  # give it time to boot

      - name: Wait for server healthcheck
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000/healthz; then
              echo "Server is ready!"
              break
            fi
            echo "Waiting for server..."
            sleep 5
          done

      - name: Run tests with coverage
        run: pytest --cov=tatou --cov-report=xml
